import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-center justify-between px-6 py-1 bg-white dark:bg-gray-800">
          <div className="flex items-center space-x-4">
            <Link href="#">
              <Image
                src="https://i.ibb.co/3rpy8jN/tumsupportlogo.jpg"
                width={100}
                height={100}
                alt="tum.supprt logo"
              />
            </Link>
            <nav className="hidden md:flex space-x-4">
              <Link
                className="text-gray-800 dark:text-white hover:text-gray-600 dark:hover:text-gray-300"
                href="#"
              >
                Home
              </Link>
            </nav>
          </div>
          <div className="flex items-center space-x-4">
            <Popover>
              <PopoverTrigger asChild>
                <Badge className="pointer">Leon</Badge>
              </PopoverTrigger>
              <PopoverContent className="w-80">
                <Card className="border-0 shadow-0">
                  <div className="p-2 space-y-2">
                    <h3 className="text-lg font-medium text-gray-700 dark:text-gray-300">
                      Current Semester
                    </h3>
                    <Badge>Spring 2023</Badge>
                    <h3 className="text-lg font-medium text-gray-700 dark:text-gray-300">
                      Study Program
                    </h3>
                    <Badge>Computer Science</Badge>
                  </div>
                </Card>
              </PopoverContent>
            </Popover>
            <Button variant="primary">Logout</Button>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
